### PR TITLE
Fix Build on GitHub Actions

### LINKED ISSUE #46: Fix build on GitHub Actions
Hi @LakshyaKhatri, hope you are doing well.

In an attempt to port the Travis build to GitHub Actions I realized too late that you had added custom instructions in Travis to authenticate remotely with CDSAPI:

```
before_install:
- openssl aes-256-cbc -K $encrypted_fbf94d2678c4_key -iv $encrypted_fbf94d2678c4_iv
  -in .cdsapirc.enc -out $HOME\/.cdsapirc -d
```

Could you please help adding these instructions to our new CI.yml workflow? I also accidentally deleted the `.cdsapirc.enc` file you added to the repository. Please feel free to revive it if necessary.

### PR DESCRIPTION
**Pull request by LakshyaKhatri**
Fixes #46

### CODE REVIEW

**Comment by LakshyaKhatri** [comment]
Hey @juliohm, sorry for the job failing email spams 🤦🏽‍♂️ 🙂, but this PR will fix the failing jobs. 
The reason it's failing here is because GitHub do not allow any new change in the workflow files to access secrets. Right now, accessing secrets here will return empty strings. I tried it on another repository of mine and here are the differences I observed:

Our repo:
Screenshot from 2022-07-31 19-11-55

My other repo:
Screenshot from 2022-07-31 19-09-54

**Comment by LakshyaKhatri** [comment]
If we choose to merge, kindly squash the commits. I made too many experimental commits in this PR. 🙏 ❤️

**Comment by juliohm** [comment]
Thank you @LakshyaKhatri for your awesome contributions as usual. I merged it, let's see if it working again. ❤️

**Comment by LakshyaKhatri** [comment]
🙈  🎉 🕺🏽
Screenshot from 2022-07-31 19-52-13

**Comment by juliohm** [comment]
That is awesome! I will try to trigger the build on master again to see if the badge becomes green.

**Comment by LakshyaKhatri** [comment]
It still seems to fail for non-linux based platforms!

**Comment by juliohm** [comment]
Yes, I noticed it. Maybe the build is failing on Windows for another reason? Download limits?

**Comment by LakshyaKhatri** [comment]
Umm, no idea! Mind if I re-open the issue to keep track of this?

**Comment by juliohm** [comment]
Please go ahead. We can comment there that Windows is the only build that is failing.

**Pull request merged**
