### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by natgeo-wong**
Allow for non-breaking update versions of Julia.

### CODE REVIEW

**Comment by juliohm** [comment]
Thank you @natgeo-wong ! So this syntax allows us to use the package with Julia v1.4, v1.5 etc right?

**Comment by LakshyaKhatri** [comment]
@juliohm The decryption command in for API keys is failing for some reason. Any idea why is that happening?

**Comment by juliohm** [comment]
I didnt check the code recently. Could you please take a look at it? You're
much more familiar with the code than I am. :)

**Comment by LakshyaKhatri** [comment]
Okay, I'm on it.

**Comment by natgeo-wong** [comment]
Opened a separate pull request here (https://github.com/JuliaClimate/CDSAPI.jl/pull/37) that includes all the changes I made to better use and log the CDSAPI

**Comment by juliohm** [comment]
Thank you. Closing this one in favor of the other :+1:

**Pull request closed without merging**
