### PR TITLE
investigate failing test suite

### PR DESCRIPTION
**Pull request by haakon-e**
In reality this PR checks that CI succeeds with no code changes, since #49 fails.

### CODE REVIEW

**Comment by haakon-e** [comment]
ah, it appears the jobs weren't triggered in this PR. cc: @LakshyaKhatri

**Comment by juliohm** [comment]
@haakon-e this PR simply adds a dot to the docstring. Am I missing something?

**Comment by haakon-e** [comment]
yeah, so the point is to prove that the change in #49 isn't the cause of failing tests. 

This leads me to suspect that either a patch release in one of the dependencies is causing tests to fail (compared to successful tests on master 3 weeks ago), or there is an issue with the CDS API outside of the Julia ecosystem.

**Comment by haakon-e** [comment]
updated the PR title to make this clearer.

**Comment by haakon-e** [comment]
Looking at the stacktrace:
```julia
ERA5 monthly preasure data: Error During Test at /Users/runner/work/CDSAPI.jl/CDSAPI.jl/test/retrieve.jl:4
[165](https://github.com/JuliaClimate/CDSAPI.jl/actions/runs/3857660781/jobs/6575325258#step:7:168)
  Got exception outside of a @test
[166](https://github.com/JuliaClimate/CDSAPI.jl/actions/runs/3857660781/jobs/6575325258#step:7:169)
  BoundsError: attempt to access 1-element Vector{SubString{String}} at index [2]
[167](https://github.com/JuliaClimate/CDSAPI.jl/actions/runs/3857660781/jobs/6575325258#step:7:170)
  Stacktrace:
[...]
```
it seems like something happens when datasets are downloaded. Are you able to check this out locally to see where/why the `BoundsError` is occurring?

**Comment by juliohm** [comment]
I mean, we know already that the build is failing due to GRIB support on Windows: https://github.com/JuliaClimate/CDSAPI.jl/issues/46

**Comment by LakshyaKhatri** [comment]
@juliohm the tests seem to be failing for other platforms as well, this couldn't be the GRIB issue 🤔

**Comment by haakon-e** [comment]
Yeah, the stacktrace I was quoting above was on macos.

**Pull request closed without merging**
